(WIP) Enabling of Knowledge Layer
COVESA/cdsp pull request #50
Opened 2024-06-03 06:32 UTC by chrizmc

This PR is intended to commit the first basic components that enable a knowledge layer in the CDSP

2024-06-03 14:27 UTC, slawr reviewed
Hi @claireqiu, thinking to the future it would be good to get a little more information into the commit messages. "add files" forces someone to look into the commit itself to find the nature of the change.

Something like "json-rdf-connector: add data struct and utils headers" or "add data struct and utils headers to json-rdf-connector" would be more informative.

2024-06-04 17:51 UTC, slawr commented
Great to see this work becoming public and new functionality being added to the Playground itself.

When we first discussed the Knowledge Layer Connector in the May 21st call I remember that we debated whether the Information Layer part should be parallel to the Knowledge Layer part or under it. One point of concern was that in parallel it might be interpreted as an abstraction layer and that whilst it can do that, it would have potentially high performance consequences for low latency and high frequency data.

To be honest I do not recall and it is not recorded in the minutes if we came to a conclusion. I do recall saying that one possible approach would be to keep it as presented here and be careful in documenting the circumstances for its use. Also that we might not limit ourselves to it whilst developing the connector as performance was an attribute we were interested in.

So what am I saying? I think we need to be clear on how we are approaching this and the planning should reflect it.

2024-06-05 08:40 UTC, chrizmc commented
I understand what you mean. One disadvantage of a structure like this
-knowledge layer
     - information layer
could be that you might think that the information layer can only be used together with the knowledge layer. But in the case of RealmDB (maybe also for IoTDB or other DBs), the websocket IF on the information layer can also be used by a simple UI app or something, without "starting" and using the knowledge layer.

But yes, I agree, we should be clear about how we want to do it....

2024-06-06 14:54 UTC, slawr commented
> I understand what you mean. One disadvantage of a structure like this -knowledge layer -- information layer could be that you might think that the information layer can only be used together with the knowledge layer. But in the case of RealmDB (maybe also for IoTDB or other DBs), the websocket IF on the information layer can also be used by a simple UI app or something, without "starting" and using the knowledge layer.

Agreed. I think you would do something like that if you were communicating that at the current state of development it is specified for the demands of the knowledge layer connector. Moving it later as it evolves. However as you go onto say that might confuse people who would like to use it for other purposes.

I understand that point. Also of course in terms of having a workaround for the fact that Realm is an Embedded Application Database normally bound into a specific application. 

> But yes, I agree, we should be clear about how we want to do it....

I think for me it is a possible communications issue around explaining the playground.

I think it's great that this PR already contains some documentation.
Of course doc will always be a challenge.
When I read the root readme for the info layer it authoritatively states the components for the playground info layer are the database handlers and router. It goes on to say data access is through this web socket server and that Realm is the single database supported.
From the viewpoint of the existing BMW UX app development and in the context of the connector I think this is good documentation but it doesn't put it in context for the more general case. 
For example:
Does this WS server handle a broad range of use cases? Is it simple single key/value get/set only for example?
How does it handles complex queries?
The Playground presented at the Autumn AMM discussed in part the possibilities of TS DBs, then if this was merged as it is now people could be confused by discussion of data access through this WS and IoTDB is not supported, but a new DB Realm is..

If I'm someone from one of the COVESA BoFs what do I understand about data access in the Playground in reading this?

Of course a balance in doc needs to be struck. We are not a supplier and people need to put some effort in.

I've not thought about it deeply, but one approach could be a large info box at the top putting the rest of the doc in context. This was developed for X,Y, Z requirements, if you want A, B, C then you may use other means such as directly accessing a component.

Does that make sense?

2024-07-09 10:43 UTC, slawr reviewed
It is not a requirement for merging but for the actual code modules you might consider adding SPDX information in a header to allow automation of license handling.

Here is an example: https://github.com/slawr/cdsp/blob/iotdb-udf-grafana/docker/iotdb/Dockerfile

2024-07-10 11:29 UTC, chrizmc commented
We will have a look into SPDX, thank's for the hint.

2024-11-13 14:52 UTC, slawr reviewed
Flagging an early review comment as the impact is somewhat large

2024-11-13 14:52 UTC, slawr commented on cdsp/information-layer/README.md
> +  "node": { "name": "Vehicle_Speed" },
An early review observation is that in your IoTDB implementation you have chosen to replace VSS dot notation with underscores to integrate and avoid conflicts with the dot notation of the IoTDB data model. Whilst a valid approach (I considered the same when creating the Playground) it is different to the one I choose which quotes the VSS name and which is used in various places. For example, the RemotiveLabs feeder, the VISSR integration and in the online documentation. See https://covesa.github.io/cdsp/manuals/apache-iotdb/#integrating-vss-data-into-the-iotdb-data-model

So we need to have an alignment discussion to resolve this.

2025-02-03 15:57 UTC, slawr commented
> We will have a look into SPDX, thank's for the hint.

Did you come to any conclusions on SPDX? I don't think it is a hard requirement for merging but as you are introducing quite a lot of functionality it would help with licensing questions and reuse.

2025-02-03 16:25 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +- **Logic Mapping in Data-Driven Rules:** Instead of hardcoded IF-ELSE logic, data-driven rules like [Datalog](https://de.wikipedia.org/wiki/Datalog) offer:
Would this be better linking to the English version of the wikipedia page rather than the German?

2025-02-04 13:07 UTC, slawr reviewed
Hi @aw-muc, why is docker/start_docker.sh an empty file? I can find no reference to its use.

2025-02-04 13:55 UTC, aw-muc commented
> Hi @aw-muc, why is docker/start_docker.sh an empty file? I can find no reference to its use.

this was initially a file that was planned to cover docker commands, but in the end it was never used and added to the pr by accident.

2025-02-04 14:33 UTC, slawr requested changes
Mix of comment and change request. For latter please fix spelling mistakes.

2025-02-04 14:33 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +In this use case, we have implemented an AI-powered solution to detect aggressive driving behaviors. Rather than relying on complex, maintenance-intensive IF-ELSE logic in code or overly sophisticate
Spelling of behaviours

2025-02-04 14:33 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
Incorrect spelling "informtion"

2025-02-04 14:33 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +To be determined (TBD).
Stating the obvious, so this is more at ToDo marker, but install and runtime instructions are missing

2025-02-04 14:33 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +- **Knowledge Layer Connector:** [RDFConvertor](../../cdsp/knowledge-layer/connector/README.md) - Converts VSS JSON format into RDF Graph format and vice versa
I notice a mismatch between this list and the associated figure, the C4 Model Component Diagram and the s/w structure.

In the list there is a logical component KL Connector that in implementation becomes RDF Converter. The C4 Model has both Connector (WS Client) and Converter (C++). If I look at the source tree the connector folder contains json-rdf-converter and websocket-client.

The C4 Model in particular is there to **communicate** high level architecture and does not necessarily have to be a detailed map to detailed implementation. I would rather readers understand the conceptual flow, than be lost trying to understand some complex detail at a lower level of abstraction, e.g code level.

That said I wonder if there is an opportunity to tighten up diagrams and text for consistency and clarity. Such as the mapping in the list. Possibly also the use of "websocket client" without reference to which for what. Similarly in the figure Data Access maps to Websocket. Would that be better as the part, rather than a protocol or a combination of the two 'X via WS'?

2025-02-04 14:35 UTC, slawr commented
> > Hi @aw-muc, why is docker/start_docker.sh an empty file? I can find no reference to its use.
> 
> this was initially a file that was planned to cover docker commands, but in the end it was never used and added to the pr by accident.

Understood. Will you push an update to remove it or is some content inbound? I think its fine to force-push if you want to remove ahead of merge.

2025-02-04 19:47 UTC, slawr requested changes
There are some comments in the review of the feeder changes. A more major issue is that the readme is out of step with the code and needs fixing - see comment for details.

2025-02-04 19:47 UTC, slawr commented on examples/remotivelabs-feeder/README.md
> +### RealmDB schema
Why is RealmDB mentioned here if the outputs are IoTDB or WS Server (which presumably takes care of the schema)? Are you intending to support direct write to Realm as well?

2025-02-04 19:47 UTC, slawr commented on examples/remotivelabs-feeder/README.md
> +  -i ID, --id ID        Element ID to include in WebSocket data. Required when output_mode is 'websocket'.
Bridge module name not renamed in line 71:

> python3 rl-iotdb-bridge.py

2025-02-04 19:47 UTC, slawr commented on examples/remotivelabs-feeder/README.md
> +For sending data to the information-layer the websocket server has to listen on `ws://localhost:8080`.
~~Is the port and URL a default or a hard-coded value? 'Has to' suggests must.~~

Looking at the bridge source this is a hard-coded value. As there is no cmd line param to change it, I would explicitly make this a configuration item in the config section as I did for IoTDB.

2025-02-05 11:20 UTC, slawr reviewed
Is some kind of note required in the _Developer Notes_ or _Setup_ sections mentioning the web socket payload schema? This may not be detailed, that might be obtained from the source, but from the user perspective if I'm using this WS mode what are the requirements for it to successfully send data to a WS server.

I do think we should be careful about creating a documentation maintenance burden and not duplicate information unnecessarily but KL and IL are introducing a lot of moving parts and we should try to help users see the boundaries so they can concentrate on the piece in hand if that makes sense.

2025-02-11 11:42 UTC, slawr reviewed
High level review of the KL and IL parts.

I notice that there are quite a few tooling config and environment files, particularly in IL. There was one that was found to be a local file that should have not been pushed. It might be worth a check through the PR file list to check the others. That said, personally if its a generic file and would help others I see no issue with say a config file for a linter being present.

2025-02-11 11:49 UTC, slawr commented
> > It is not a requirement for merging but for the actual code modules you might consider adding SPDX information in a header to allow automation of license handling.
> > Here is an example: https://github.com/slawr/cdsp/blob/iotdb-udf-grafana/docker/iotdb/Dockerfile
> 
> Hi @slawr , I am new in the project and took over the SPDX topic. From my understanding there are different detail levels for adding license information:
> 
>     * For the project level there is already a LICENSE file
> 
>     * SPDX information inside of Docker files would add the license for the different modules
> 
>     * And finally we could add the SPDX information to each of our source files
> 
> 
> Would it be fine for you, if we add SPDX-License-Identifier MPL-2.0 to the Docker and Docker Compose files? For Information Layer this is not a problem, but the Knowledge Layer has no dockerization yet. So for now i would just add it to the IL.

Hi @Dennis-Sch, welcome to the project! 

Yes I think that would be a sensible approach.

Please ensure your commits have a signed-off. As they will add important license information ideally I think there should be traceability to BMW, either the signed-off having a BMW email address or your Github account showing you work for BMW. Does that make sense?

2025-02-12 09:29 UTC, Dennis-Sch commented
Hi @slawr ,
Thanks for the clarification, we will add SPDX also to all source files.

The final commits with the BMW connection and possible sigh-off will be done by @chrizmc
I will be just supporting here and there a bit. 

Thanks again :)

2025-04-22 14:27 UTC, slawr commented on cdsp/information-layer/README.md
> +See [hier](./router/README.md#Install) how to install the Database-Router.
Does not appear to be in current code version. Closing

2025-04-22 14:33 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
Fixed or removed. Resolving

2025-04-22 14:33 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +In this use case, we have implemented an AI-powered solution to detect aggressive driving behaviors. Rather than relying on complex, maintenance-intensive IF-ELSE logic in code or overly sophisticate
No longer present in latest code. Resolving conversation

2025-04-22 14:35 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
Not present in latest code. Resolving

2025-04-22 14:37 UTC, slawr commented on cdsp/information-layer/README.md
> +  "node": { "name": "Vehicle_Speed" },
@chrizmc code changed to dot notation correct?

2025-04-22 14:45 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
@chrizmc Remains an issue in the current code

2025-04-22 14:45 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +In this use case, we have implemented an AI-powered solution to detect aggressive driving behaviors. Rather than relying on complex, maintenance-intensive IF-ELSE logic in code or overly sophisticate
@chrizmc Remains an issue in the current code

2025-04-22 14:45 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
@chrizmc Remains an issue in the current code

2025-04-22 14:46 UTC, slawr commented on examples/knowledgelayer-hello-world/README.md
> +- **Knowledge Layer Connector:** [RDFConvertor](../../cdsp/knowledge-layer/connector/README.md) - Converts VSS JSON format into RDF Graph format and vice versa
@chrizmc how was this resolved?

2025-04-23 05:33 UTC, chrizmc commented on cdsp/information-layer/README.md
> +  "node": { "name": "Vehicle_Speed" },
yes

2025-04-23 05:49 UTC, chrizmc commented on examples/knowledgelayer-hello-world/README.md
> +- **Logic Mapping in Data-Driven Rules:** Instead of hardcoded IF-ELSE logic, data-driven rules like [Datalog](https://de.wikipedia.org/wiki/Datalog) offer:
solved with commit c7a612635f24908bc225febbae0d793191925711

2025-04-23 10:50 UTC, slawr commented on examples/remotivelabs-feeder/README.md
> +For sending data to the information-layer the websocket server has to listen on `ws://localhost:8080`.
@chrizmc its getting on for three months since this comment. The PR is now a large code base that touches many parts of the Playground, so not getting it merged causes some development speed friction as you are either rebasing this a lot or related code on it. With that in mind something like this perhaps fits into the category of improvement backlog, rather than a gate blocking merge. The feeder could do with better runtime configuration anyway for our additions, so that could be done at the same time.

There are others here likely in the same category. We should discuss/categorize so we can efficiently both move towards the merge and know what lies on the other side in terms of back log.

2025-04-23 11:02 UTC, chrizmc commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
fixed with 01b5dc0f31d742b785e4c5960eb056dec81785f4

2025-04-23 11:03 UTC, chrizmc commented on examples/knowledgelayer-hello-world/README.md
> +In this use case, we have implemented an AI-powered solution to detect aggressive driving behaviors. Rather than relying on complex, maintenance-intensive IF-ELSE logic in code or overly sophisticate
fixed with 01b5dc0f31d742b785e4c5960eb056dec81785f4

2025-04-23 11:03 UTC, chrizmc commented on examples/knowledgelayer-hello-world/README.md
> +Live VSS data from the current drive made accesible in the [Information Layer](../../cdsp/information-layer/README.md) via [Websocket](../../cdsp/information-layer/router/src/websocket-server.js) are
fixed with 01b5dc0f31d742b785e4c5960eb056dec81785f4

2025-04-23 11:04 UTC, chrizmc commented on examples/knowledgelayer-hello-world/README.md
> +- **Knowledge Layer Connector:** [RDFConvertor](../../cdsp/knowledge-layer/connector/README.md) - Converts VSS JSON format into RDF Graph format and vice versa
fully agree, there were lot of mismatches in namings etc. Now it should be fixed with 01b5dc0f31d742b785e4c5960eb056dec81785f4

2025-04-23 11:20 UTC, chrizmc commented on docker/docker-compose-cdsp.yml
every IL and KL component is dockerized meanwhile

2025-05-07 17:51 UTC, slawr commented on examples/remotivelabs-feeder/README.md
> +For sending data to the information-layer the websocket server has to listen on `ws://localhost:8080`.
Pick this up #post-merge

2025-05-08 12:04 UTC, slawr approved these changes
Whilst there are some review comments outstanding the maintainers have agreed there are no known show stoppers and it is preferable to get this last change set merged and to then make improvements

2025-05-08 13:33 UTC, merged